### ISSUE TITLE
Since I added mdns to my android only flutter project its not compiling anymore

### ISSUE THREAD

**Issue by gizmomogwai** [platinumjam/flutter_mdns#1]
I want to compile android only on os x.
Without this dependency it works, with it, flutter crashes with this in the log
````
String: Exit code 1 from: /usr/bin/xcodebuild -project /Users/gizmo/Dropbox/Documents/_projects/dotstar/mobile/ios/Runner.xcodeproj -target Runner -showBuildSettings

#0      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:341)
#1      runCheckedSync (package:flutter_tools/src/base/process.dart:273)
#2      XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart:99)
#3      CocoaPods.setupPodfile (package:flutter_tools/src/ios/cocoapods.dart:114)
#4      injectPlugins (package:flutter_tools/src/plugins.dart:246)
#5      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:62)
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:278)
<asynchronous suspension>
#7      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#10     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#11     new Future.sync (dart:async/future.dart:222)
````

**Comment by gizmomogwai** [comment]
When xcode is installed its not a problem.

**Comment by platinumjam** [comment]
It seems like this issue plagued some standard flutter plugins for a while as well. I'll see if I can find out more information on how to resolve the issue.
